require('./mongoose/mongoose')
const morgan=require('morgan')
const express=require('express')
const user=require('./routers/Userprofile')
const postRouter=require('./routers/postRouter')
const friend=require('./routers/friendFollowRouters')
const userRouter=require('./routers/UserSignUpRouter')
const dotenv=require('dotenv')
dotenv.config()
var app=express()
app.use(express.json())
app.use(morgan("common"))
app.use(express.urlencoded({extended:true}))
const PORT=process.env.PORT || 3000
app.use('/user',userRouter)
app.use('/profile',user)
app.use('/post',postRouter)
app.use('/post',friend)

app.listen(PORT,function(){console.log( PORT,'service Started ')})
